import logging
import os
import uuid
from contextvars import ContextVar
from typing import Awaitable, Callable, Dict, List, Optional

from fastapi import FastAPI, HTTPException, Query, Request, status
from fastapi.responses import JSONResponse
from starlette.middleware.base import BaseHTTPMiddleware

from database import db
from logging_config import client_ip, configure_logging, get_logger
from models import Account, AccountCreate, AccountList, AccountSummary


SERVICE_NAME = "account-details-api"
SERVICE_VERSION = "1.0.0"

# Correlation ID per request — generated by middleware, read by handlers.
request_id_ctx: ContextVar[str] = ContextVar("request_id", default="-")


configure_logging(level=os.getenv("LOG_LEVEL", "INFO").upper())
logger = get_logger("account_details.api")


class RequestContextMiddleware(BaseHTTPMiddleware):
    """Assigns a request ID, logs request/response, and surfaces errors."""

    async def dispatch(
        self,
        request: Request,
        call_next: Callable[[Request], Awaitable[Response]],
    ) -> Response:
        rid = request.headers.get("x-request-id") or uuid.uuid4().hex
        token = request_id_ctx.set(rid)
        start = request.url.path
        try:
            logger.info(
                "request.received",
                extra={
                    "request_id": rid,
                    "service": SERVICE_NAME,
                    "method": request.method,
                    "path": start,
                    "client_ip": client_ip(request),
                },
            )
            response = await call_next(request)
        except Exception:
            logger.exception(
                "request.unhandled_error",
                extra={
                    "request_id": rid,
                    "service": SERVICE_NAME,
                    "method": request.method,
                    "path": start,
                },
            )
            return JSONResponse(
                status_code=500,
                content={"error": "internal_server_error", "request_id": rid},
                headers={"x-request-id": rid},
            )
        finally:
            request_id_ctx.reset(token)

        response.headers["x-request-id"] = rid
        logger.info(
            "request.completed",
            extra={
                "request_id": rid,
                "service": SERVICE_NAME,
                "method": request.method,
                "path": start,
                "status_code": response.status_code,
            },
        )
        return response


app = FastAPI(
    title="Account Details API",
    description="A simple FastAPI service to fetch and manage account details.",
    version=SERVICE_VERSION,
)
app.add_middleware(RequestContextMiddleware)


@app.on_event("startup")
def on_startup() -> None:
    logger.info(
        "service.startup",
        extra={"service": SERVICE_NAME, "version": SERVICE_VERSION},
    )


@app.on_event("shutdown")
def on_shutdown() -> None:
    logger.info(
        "service.shutdown",
        extra={"service": SERVICE_NAME, "version": SERVICE_VERSION},
    )


@app.get("/", tags=["Health"])
def root() -> dict:
    return {"status": "ok", "service": SERVICE_NAME}


@app.get("/health", tags=["Health"])
def health() -> dict:
    return {"status": "healthy"}


@app.get(
    "/accounts",
    response_model=AccountList,
    tags=["Accounts"],
    summary="List all accounts",
)
def list_accounts(
    account_type: Optional[str] = Query(
        None,
        pattern="^(savings|checking|business)$",
        description="Filter by account type",
    ),
) -> AccountList:
    accounts = db.list_all(account_type=account_type)
    logger.info(
        "accounts.listed",
        extra={
            "request_id": request_id_ctx.get(),
            "filter_account_type": account_type,
            "returned": len(accounts),
        },
    )
    return AccountList(
        total=len(accounts),
        accounts=[
            AccountSummary(
                id=a.id,
                name=a.name,
                email=a.email,
                account_type=a.account_type,
            )
            for a in accounts
        ],
    )


@app.get(
    "/accounts/{account_id}",
    response_model=Account,
    tags=["Accounts"],
    summary="Fetch a single account by ID",
)
def get_account(account_id: int) -> Account:
    account = db.get(account_id)
    if not account:
        logger.info(
            "accounts.get.not_found",
            extra={"request_id": request_id_ctx.get(), "account_id": account_id},
        )
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Account with id {account_id} not found",
        )
    logger.info(
        "accounts.get.success",
        extra={"request_id": request_id_ctx.get(), "account_id": account_id},
    )
    return account


@app.post(
    "/accounts",
    response_model=Account,
    status_code=status.HTTP_201_CREATED,
    tags=["Accounts"],
    summary="Create a new account",
)
def create_account(payload: AccountCreate) -> Account:
    account = db.create(payload)
    logger.info(
        "accounts.created",
        extra={
            "request_id": request_id_ctx.get(),
            "account_id": account.id,
            "account_type": account.account_type,
            "email_domain": account.email.split("@", 1)[-1],
        },
    )
    return account


@app.exception_handler(HTTPException)
def http_exception_handler(_request: Request, exc: HTTPException) -> JSONResponse:
    logger.warning(
        "http_exception",
        extra={
            "request_id": request_id_ctx.get(),
            "status_code": exc.status_code,
            "detail": str(exc.detail),
        },
    )
    return JSONResponse(
        status_code=exc.status_code,
        content={"error": exc.detail, "request_id": request_id_ctx.get()},
    )
